version: "3.2"
services:
  gateway:
    image: nginx
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  
  api:
    image: generic-ml-api
    build: ./
    command: "gunicorn --bind 0.0.0.0:5000 service:app"
    volumes: 
      - ./model_checkpoints:/src/model_checkpoints
      - ./datasets:/src/datasets


  api2:
    image: generic-ml-api
    build: ./
    command: "gunicorn --bind 0.0.0.0:5000 service:app"
    volumes: 
      - ./model_checkpoints:/src/model_checkpoints
      - ./datasets:/src/datasets
